/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A wasm constant expression, used to initialize a global.
 *
 * Construct one with the factory statics ([`ConstExpr::i32`],
 * [`ConstExpr::ref_null`], ...) and pass it to `globals.addLocal`.
 */
export declare class ConstExpr {
  /** A constant `i32` value. */
  static i32(v: number): ConstExpr
  /**
   * A constant `i64` value.
   *
   * Takes a JS `bigint`. napi's `BigInt::get_i64` also reports whether the
   * value fit losslessly in an `i64`; we intentionally ignore that flag and
   * take the low 64 bits, mirroring wasm's wraparound `i64` semantics (an
   * out-of-range `bigint` is truncated, not rejected).
   */
  static i64(v: bigint): ConstExpr
  /**
   * A constant `f32` value.
   *
   * napi has no 32-bit float argument type, so this takes a JS `number`
   * (`f64`) and narrows it to `f32`.
   */
  static f32(v: number): ConstExpr
  /** A constant `f64` value. */
  static f64(v: number): ConstExpr
  /**
   * A constant `v128` value from exactly 16 little-endian bytes.
   *
   * Rejects any other length with a catchable error (never a process-aborting
   * panic). The byte order matches walrus' own `v128` decoding: byte 0 is the
   * least-significant.
   */
  static v128(bytes: Uint8Array): ConstExpr
  /**
   * A constant that reads the current value of another global
   * (`global.get $g`).
   */
  static globalGet(global: WasmGlobal): ConstExpr
  /**
   * A null reference of the given heap type (`ref.null`).
   *
   * `ref.null` is ALWAYS nullable — a non-nullable null is invalid wasm
   * (`WebAssembly.validate` rejects it), so this factory takes only the heap
   * type and always builds a nullable `RefType`.
   *
   * Fallible because the heap type conversion rejects concrete/indexed heap
   * types (they need a type handle, deferred to the GC-types task).
   */
  static refNull(heap: HeapType): ConstExpr
  /** Which kind of constant expression this is. */
  get kind(): ConstExprKind
}

export declare class ModuleConfig {
  constructor()
  /**
   * Sets a flag to whether DWARF debug sections are generated for this
   * module.
   *
   * By default this flag is `false`. Note that any emitted DWARF is
   * currently wildly incorrect and buggy, and is also larger than the wasm
   * itself!
   */
  generateDwarf(generateDwarf: boolean): this
  /**
   * Sets a flag to whether the custom "name" section is generated for this
   * module.
   *
   * The "name" section contains symbol names for the module, functions, and
   * locals. When enabled, stack traces will use these names, instead of
   * `wasm-function[123]`.
   *
   * By default this flag is `true`.
   */
  generateNameSection(generateNameSection: boolean): this
  /**
   * Sets a flag to whether synthetic debugging names are generated for
   * anonymous locals/functions/etc when parsing and running passes for this
   * module.
   *
   * By default this flag is `false`, and it will generate quite a few names
   * if enabled!
   */
  generateSyntheticNamesForAnonymousItems(generateSyntheticNamesForAnonymousItems: boolean): this
  /**
   * Indicates whether the module, after parsing, performs strict validation
   * of the wasm module to adhere with the current version of the wasm
   * specification.
   *
   * This can be expensive for some modules and strictly isn't required to
   * create a `Module` from a wasm file. This includes checks such as "atomic
   * instructions require a shared memory".
   *
   * By default this flag is `true`
   */
  strictValidate(strictValidate: boolean): this
  /**
   * Indicates whether the module will have the "producers" custom section
   * which preserves the original producers and also includes `walrus`.
   *
   * This is generally used for telemetry in browsers, but for otherwise tiny
   * wasm binaries can add some size to the binary.
   *
   * By default this flag is `true`
   */
  generateProducersSection(generateProducersSection: boolean): this
  /**
   * Indicates whether this module is allowed to use only stable WebAssembly
   * features or not.
   *
   * This is currently used to disable some validity checks required by the
   * WebAssembly specification. It's not religiously adhered to throughout
   * the codebase, even if set to `true` some unstable features may still be
   * allowed.
   *
   * By default this flag is `false`
   */
  onlyStableFeatures(onlyStableFeatures: boolean): this
  /**
   * Sets a flag to whether code transform is preverved during parsing.
   *
   * By default this flag is `false`.
   */
  preserveCodeTransform(preserve: boolean): this
  parse(binary: Uint8Array): WasmModule
}

/**
 * The custom sections of a module. Mutations write straight through to the
 * owning [`WasmModule`].
 */
export declare class WasmCustomSections {
  /**
   * Add a raw, unparsed custom section with the given name and data.
   *
   * Names starting with `.debug` are rejected: walrus manages DWARF debug
   * sections through its own parsed representation and silently drops any
   * `.debug*` custom section from `emitWasm` output, so adding one here would
   * be lost data. Add real debug info through the module's DWARF handling
   * instead.
   */
  addRaw(name: string, data: Uint8Array): void
  /**
   * Remove the first raw custom section with the given name, returning its
   * data if it was present.
   */
  removeRaw(name: string): Uint8Array | null
  /**
   * List the custom sections currently present in the module. `data` is the
   * raw bytes for unparsed (raw) sections, or `null` for sections that walrus
   * has parsed into a typed representation.
   */
  list(): Array<RawSectionInfo>
}

/**
 * A single data segment in a module, as a live handle: it holds the segment's
 * id plus a strong reference to the owning [`WasmModule`], and every accessor
 * reads or writes through to that module.
 */
export declare class WasmData {
  /**
   * This segment's stable index — its identity for numeric lookup. Readable
   * even after the segment is deleted (it never touches the arena).
   */
  get index(): number
  /** This segment's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this segment's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /** Whether this segment is active or passive (read only). */
  get kind(): DataKindTag
  /** This segment's payload bytes. */
  get value(): Uint8Array
  /**
   * Set this segment's payload bytes. Bytes are freely mutable (no validation —
   * mirror-walrus policy).
   */
  set value(bytes: Uint8Array)
  /**
   * The memory this active segment initializes, or `null` if it is passive.
   *
   * A method (not a getter) because it materializes a fresh [`WasmMemory`]
   * wrapper on each call.
   */
  memory(): WasmMemory | null
  /**
   * This active segment's initialization offset as a [`ConstExpr`], or `null`
   * if it is passive.
   *
   * A method (not a getter) because it materializes a fresh `ConstExpr` wrapper
   * on each call.
   */
  offset(): ConstExpr | null
}

/**
 * The data segments of a module. Each accessor materializes a fresh
 * [`WasmData`] handle that reads and writes straight through to the owning
 * [`WasmModule`]; the collection itself caches nothing.
 */
export declare class WasmDataSegments {
  /** The number of data segments in the module. */
  get length(): number
  /** Every data segment in the module, as live item handles. */
  items(): Array<WasmData>
  /**
   * The data segment whose stable `.index` equals `index`, or `null` if none
   * exists.
   */
  getByIndex(index: number): WasmData | null
  /**
   * Delete a data segment from the module. Takes the handle itself: a JS number
   * can never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted segment (walrus does not check; a dangling `memory.init` /
   * `data.drop` would abort emit).
   *
   * Same no-panic invariant as the item accessors: walrus' `ModuleData::delete`
   * asserts the id is live, and a panic across FFI aborts the process. Id
   * equality includes the arena_id, so this liveness scan rejects BOTH
   * already-deleted ids (`iter()` skips tombstoned entries) AND handles that
   * belong to a different module (arena_id mismatch), surfacing a catchable JS
   * error instead of aborting.
   */
  delete(data: WasmData): void
  /**
   * Add a new passive data segment, returning a live handle to it.
   *
   * A passive segment carries only its payload bytes; it is copied into a
   * memory on demand via `memory.init`. `value` is freely chosen (bytes are not
   * validated — mirror-walrus policy).
   *
   * The returned handle holds its own strong reference to the module (same as
   * the accessor handles), so it stays valid as long as it is held.
   */
  addPassive(value: Uint8Array): WasmData
  /**
   * Add a new active data segment, returning a live handle to it.
   *
   * An active segment is copied into `memory` at `offset` (a constant
   * expression) at instantiation time. `value` is freely chosen (bytes are not
   * validated — mirror-walrus policy).
   *
   * `add_active` is a CONSUME site for arena ids: both the `memory` handle and
   * any ids embedded in `offset` are resolved by walrus at emit via panicking
   * index lookups, and a panic across FFI ABORTS the whole Node process. So we
   * validate both BEFORE touching the arena:
   *   1. the `memory` handle must be live in THIS module (a foreign/deleted
   *      MemoryId would abort `get_memory_index`), and
   *   2. every id in `offset` must be live in THIS module
   *      (`validate_const_expr` — a foreign/deleted Global/RefFunc/typed-RefNull
   *      id would abort `get_global_index`/`get_func_index`/`get_type_index`).
   * Either check failing yields a catchable JS error and leaves the module
   * untouched.
   *
   * Per mirror-walrus policy this adds NO wasm semantic-validity checks: the
   * offset is not range-checked against the memory's size, nor is its value
   * type matched to the memory's index type. A semantically-invalid-but-stored
   * module is the caller's responsibility, catchable via `WebAssembly.validate`
   * / re-parse.
   */
  addActive(memory: WasmMemory, offset: ConstExpr, value: Uint8Array): WasmData
}

/**
 * A single element segment in a module, as a live handle: it holds the
 * segment's id plus a strong reference to the owning [`WasmModule`], and every
 * accessor reads or writes through to that module.
 *
 * READ + delete only — building a new element segment (`add`) needs
 * function-list / expression-list id validation and is a deliberate later task.
 */
export declare class WasmElement {
  /**
   * This segment's stable index — its identity for numeric lookup. Readable
   * even after the segment is deleted (it never touches the arena).
   */
  get index(): number
  /** This segment's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this segment's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /** Whether this segment is passive, declared, or active (read only). */
  get kind(): ElementKindTag
  /**
   * The table this active segment initializes, or `null` if it is passive or
   * declared.
   *
   * A method (not a getter) because it materializes a fresh [`WasmTable`]
   * wrapper on each call.
   */
  table(): WasmTable | null
  /**
   * This active segment's initialization offset as a [`ConstExpr`], or `null`
   * if it is passive or declared.
   *
   * A method (not a getter) because it materializes a fresh `ConstExpr` wrapper
   * on each call.
   */
  offset(): ConstExpr | null
  /**
   * Whether this segment's items are function references (`Functions`) or
   * constant expressions (`Expressions`) (read only).
   */
  get itemsKind(): ElementItemsTag
  /**
   * The functions this segment references, as live [`WasmFunction`] handles, or
   * `null` if this segment's items are constant expressions (`Expressions`).
   *
   * A method (not a getter) because it materializes fresh `WasmFunction`
   * wrappers on each call. The order matches the segment's item order.
   */
  functionItems(): Array<WasmFunction> | null
  /**
   * The element type of this segment's expression items as a [`ValType`] (the
   * `Ref` variant), or `null` if this segment's items are function references
   * (`Functions`).
   *
   * Fallible: the ref's heap type may embed a `#[non_exhaustive]` walrus heap
   * variant a later 0.26.x adds; that surfaces as a catchable JS error, never a
   * process-aborting panic.
   */
  expressionElementType(): ValType | null
  /**
   * This segment's constant-expression items as [`ConstExpr`] wrappers, or
   * `null` if this segment's items are function references (`Functions`).
   *
   * A method (not a getter) because it materializes fresh `ConstExpr` wrappers
   * on each call. Read only: the items are cloned out, so no id validation is
   * needed (that would only be required when building a new segment).
   */
  expressionItems(): Array<ConstExpr> | null
}

/**
 * The element segments of a module. Each accessor materializes a fresh
 * [`WasmElement`] handle that reads and writes straight through to the owning
 * [`WasmModule`]; the collection itself caches nothing.
 */
export declare class WasmElements {
  /** The number of element segments in the module. */
  get length(): number
  /** Every element segment in the module, as live item handles. */
  items(): Array<WasmElement>
  /**
   * The element segment whose stable `.index` equals `index`, or `null` if none
   * exists.
   */
  getByIndex(index: number): WasmElement | null
  /**
   * Delete an element segment from the module. Takes the handle itself: a JS
   * number can never be turned back into a walrus id, so the wrapper is the
   * only way to name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted segment (walrus does not check; a dangling `table.init` /
   * `elem.drop` would abort emit).
   *
   * Same no-panic invariant as the item accessors: walrus'
   * `ModuleElements::delete` asserts the id is live, and a panic across FFI
   * aborts the process. Id equality includes the arena_id, so this liveness
   * scan rejects BOTH already-deleted ids (`iter()` skips tombstoned entries)
   * AND handles that belong to a different module (arena_id mismatch),
   * surfacing a catchable JS error instead of aborting.
   */
  delete(element: WasmElement): void
}

/**
 * A single export in a module, as a live handle: it holds the export's id plus
 * a strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmExport {
  /**
   * This export's stable index — its identity for numeric lookup. Readable even
   * after the export is deleted (it never touches the arena).
   */
  get index(): number
  /** The name this item is exported under. */
  get name(): string
  /** Set the name this item is exported under. */
  set name(name: string)
  /** The kind of item this export exposes (read only). */
  get kind(): ExportItemTag
  /**
   * The exported function as a live [`WasmFunction`] handle, or `null` if this
   * export is not a function.
   *
   * A method (not a getter) because it materializes a fresh wrapper on each
   * call. Wrapping the id is a pure cross-link; a later access on the returned
   * handle self-guards against the target having been deleted.
   */
  func(): WasmFunction | null
  /**
   * The exported table as a live [`WasmTable`] handle, or `null` if this export
   * is not a table.
   */
  table(): WasmTable | null
  /**
   * The exported memory as a live [`WasmMemory`] handle, or `null` if this
   * export is not a memory.
   */
  memory(): WasmMemory | null
  /**
   * The exported global as a live [`WasmGlobal`] handle, or `null` if this
   * export is not a global.
   */
  global(): WasmGlobal | null
  /**
   * The exported tag as a live [`WasmTag`] handle, or `null` if this export is
   * not a tag.
   */
  tag(): WasmTag | null
}

/**
 * The exports of a module. Each accessor materializes a fresh [`WasmExport`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 */
export declare class WasmExports {
  /** The number of exports in the module. */
  get length(): number
  /** Every export in the module, as live item handles. */
  items(): Array<WasmExport>
  /** The export whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmExport | null
  /**
   * The export with the given `name`, or `null` if none exists. Exports have no
   * name index in walrus, so this scans (the id-bridge "scan and return the
   * real id" design); export names are unique in a valid module.
   */
  byName(name: string): WasmExport | null
  /**
   * Delete an export from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * Unlike active data/element segments, an export id is NOT stored in any
   * parser-maintained back-link set that gc/emit dereferences (verified: no
   * `exports.get(<id>)` call exists in walrus' passes/emit — exports are read
   * only via `exports.iter()`). So a plain guarded delete is sufficient — there
   * is no back-link to clean. Id equality includes the arena_id, so this
   * liveness scan rejects BOTH already-deleted ids AND handles from a different
   * module, surfacing a catchable JS error instead of tripping walrus'
   * `delete` assertion and aborting the process across FFI.
   */
  delete(handle: WasmExport): void
  /**
   * Export the given function under `name`, returning a live handle to the new
   * export.
   *
   * `add_function` is a CONSUME site for an arena id: walrus stores the raw
   * `FunctionId` and resolves it to an index at emit via a panicking
   * `get_func_index`; a foreign-module or already-deleted handle would abort
   * the whole Node process there. We reject such an id with a catchable error
   * BEFORE touching the arena, so a failed add never mutates the module. Same
   * id-ref rule as `data.addActive` / `tags.add`.
   */
  addFunction(name: string, func: WasmFunction): WasmExport
  /**
   * Export the given table under `name`, returning a live handle to the new
   * export. The table must belong to THIS module (id-ref guard; see
   * [`WasmExports::add_function`]).
   */
  addTable(name: string, table: WasmTable): WasmExport
  /**
   * Export the given memory under `name`, returning a live handle to the new
   * export. The memory must belong to THIS module (id-ref guard; see
   * [`WasmExports::add_function`]).
   */
  addMemory(name: string, memory: WasmMemory): WasmExport
  /**
   * Export the given global under `name`, returning a live handle to the new
   * export. The global must belong to THIS module (id-ref guard; see
   * [`WasmExports::add_function`]).
   */
  addGlobal(name: string, global: WasmGlobal): WasmExport
  /**
   * Export the given tag under `name`, returning a live handle to the new
   * export. The tag must belong to THIS module (id-ref guard; see
   * [`WasmExports::add_function`]).
   */
  addTag(name: string, tag: WasmTag): WasmExport
}

/**
 * A single function in a module, as a live handle: it holds the function's id
 * plus a strong reference to the owning [`WasmModule`], and every accessor
 * reads or writes through to that module.
 *
 * Only metadata is exposed here — the function's kind, name, and type. The
 * function body (instructions) and the import handle for imported functions are
 * deferred to later tasks.
 */
export declare class WasmFunction {
  /**
   * This function's stable index — its identity for numeric lookup. Readable
   * even after the function is deleted (it never touches the arena).
   */
  get index(): number
  /** This function's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this function's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /**
   * Whether this function is imported, locally defined, or an uninitialized
   * placeholder (read only).
   */
  get kind(): FunctionKindTag
  /**
   * This function's type, as a live [`WasmType`] handle into the module's type
   * arena.
   *
   * A method (not a getter) because it materializes a fresh `WasmType` wrapper
   * on each call. walrus' `Function::ty()` is a unified, panic-free accessor
   * across all three kinds (import/local/uninitialized), so the only failure
   * mode is the delete guard.
   */
  ty(): WasmType
  /**
   * The import that brings this function into the module, as a live
   * [`WasmImport`] handle, or `null` if this function is locally defined (or an
   * uninitialized placeholder).
   *
   * A method (not a getter) because it materializes a fresh wrapper on each
   * call. Wrapping the id is a pure cross-link (the reverse of
   * `WasmImport.func()`); a later access on the returned handle self-guards
   * against the import having been deleted.
   */
  import(): WasmImport | null
}

/**
 * The functions of a module. Each accessor materializes a fresh [`WasmFunction`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 */
export declare class WasmFunctions {
  /** The number of functions in the module (imported and locally defined). */
  get length(): number
  /** Every function in the module, as live item handles. */
  items(): Array<WasmFunction>
  /**
   * The function whose stable `.index` equals `index`, or `null` if none
   * exists.
   */
  getByIndex(index: number): WasmFunction | null
  /**
   * The first function with the given name, or `null` if none is named that.
   *
   * The name matched is the wasm "name" custom section name, not the export
   * name. walrus preserves function names through parsing, so a name from the
   * source module is findable here.
   */
  byName(name: string): WasmFunction | null
  /**
   * Delete a function from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted function (walrus does not check, and a dangling `call`/export/table
   * element aborts at emit time).
   *
   * Same no-panic invariant as the item accessors: walrus'
   * `ModuleFunctions::delete` tombstones the arena entry and a later access
   * asserts liveness, and a panic across FFI aborts the process. Id equality
   * includes the arena_id, so this liveness scan rejects BOTH already-deleted
   * ids (`iter()` skips tombstoned entries) AND handles that belong to a
   * different module (arena_id mismatch), surfacing a catchable JS error
   * instead of aborting.
   */
  delete(func: WasmFunction): void
}

/**
 * A single global in a module, as a live handle: it holds the global's id plus
 * a strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmGlobal {
  /**
   * This global's stable index — its identity for numeric lookup. Readable
   * even after the global is deleted (it never touches the arena).
   */
  get index(): number
  /** This global's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this global's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /** Whether this global is mutable. */
  get mutable(): boolean
  /** Set whether this global is mutable. */
  set mutable(value: boolean)
  /** Whether this global is shared (a creation-time property, read only). */
  get shared(): boolean
  /** This global's value type (read only). */
  get ty(): ValType
  /** Whether this global is imported or locally defined (read only). */
  get kind(): GlobalKind
  /**
   * This global's constant initializer, or `null` if it is imported.
   *
   * A locally defined global carries a `ConstExpr` initializer; an imported
   * global's initial value lives in the host, so this returns `null` for it.
   * A method (not a getter) because it materializes a fresh `ConstExpr`
   * wrapper on each call.
   */
  init(): ConstExpr | null
  /**
   * The import that brings this global into the module, as a live
   * [`WasmImport`] handle, or `null` if this global is locally defined.
   *
   * A method (not a getter) because it materializes a fresh wrapper on each
   * call. Wrapping the id is a pure cross-link (the reverse of
   * `WasmImport.global()`); a later access on the returned handle self-guards
   * against the import having been deleted.
   */
  import(): WasmImport | null
}

/**
 * The globals of a module. Each accessor materializes a fresh [`WasmGlobal`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 */
export declare class WasmGlobals {
  /** The number of globals in the module. */
  get length(): number
  /** Every global in the module, as live item handles. */
  items(): Array<WasmGlobal>
  /** The global whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmGlobal | null
  /** The first global with the given name, or `null` if none is named that. */
  byName(name: string): WasmGlobal | null
  /**
   * Delete a global from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted global (walrus does not check).
   *
   * Same no-panic invariant as the item accessors: walrus'
   * `ModuleGlobals::delete` asserts the id is live, and a panic across FFI
   * aborts the process. Id equality includes the arena_id, so this liveness
   * scan rejects BOTH already-deleted ids (`iter()` skips tombstoned entries)
   * AND handles that belong to a different module (arena_id mismatch),
   * surfacing a catchable JS error instead of aborting.
   */
  delete(global: WasmGlobal): void
  /**
   * Add a new locally defined global, returning a live handle to it.
   *
   * `ty` is the global's value type (e.g. `{ type: 'I32' }` or a `Ref`), and
   * `init` is its constant initializer (build one with the `ConstExpr`
   * factories). Fallible: an unsupported `ty` — currently a concrete/indexed
   * ref type, which needs a type handle we do not yet thread through — is
   * rejected with a catchable error rather than aborting.
   *
   * The returned handle holds its own strong reference to the module (same as
   * the accessor handles), so it stays valid as long as it is held.
   */
  addLocal(ty: ValType, mutable: boolean, shared: boolean, init: ConstExpr): WasmGlobal
}

/**
 * A single import in a module, as a live handle: it holds the import's id plus
 * a strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmImport {
  /**
   * This import's stable index — its identity for numeric lookup. Readable even
   * after the import is deleted (it never touches the arena).
   */
  get index(): number
  /** The module name this item is imported from (e.g. `"env"`). */
  get module(): string
  /** Set the module name this item is imported from. */
  set module(module: string)
  /** The field name of this import within its module. */
  get name(): string
  /** Set the field name of this import within its module. */
  set name(name: string)
  /** The kind of item this import brings in (read only). */
  get kind(): ImportKindTag
  /**
   * The imported function as a live [`WasmFunction`] handle, or `null` if this
   * import is not a function.
   *
   * A method (not a getter) because it materializes a fresh wrapper on each
   * call. Wrapping the id is a pure cross-link; a later access on the returned
   * handle self-guards against the target having been deleted.
   */
  func(): WasmFunction | null
  /**
   * The imported table as a live [`WasmTable`] handle, or `null` if this import
   * is not a table.
   */
  table(): WasmTable | null
  /**
   * The imported memory as a live [`WasmMemory`] handle, or `null` if this
   * import is not a memory.
   */
  memory(): WasmMemory | null
  /**
   * The imported global as a live [`WasmGlobal`] handle, or `null` if this
   * import is not a global.
   */
  global(): WasmGlobal | null
  /**
   * The imported tag as a live [`WasmTag`] handle, or `null` if this import is
   * not a tag.
   */
  tag(): WasmTag | null
}

/**
 * The imports of a module. Each accessor materializes a fresh [`WasmImport`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 *
 * Import *creation* is exposed via the typed `add*` methods, symmetric with the
 * typed adds on [`crate::exports::WasmExports`]. Each creates the imported item
 * plus its import record in one call and returns the ITEM handle (the
 * [`WasmImport`] itself is reachable via `item.import()`).
 */
export declare class WasmImports {
  /** The number of imports in the module. */
  get length(): number
  /** Every import in the module, as live item handles. */
  items(): Array<WasmImport>
  /** The import whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmImport | null
  /** The import with the given `module` and `name`, or `null` if none exists. */
  find(module: string, name: string): WasmImport | null
  /**
   * Delete an import from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * Deleting an import that still has a defined item (the imported function /
   * table / memory / global / tag) ORPHANS that item, producing a wasm-invalid
   * module — the caller's responsibility, catchable via `WebAssembly.validate`
   * / re-parse (mirror-walrus policy: we do not try to prevent it).
   *
   * Unlike active data/element segments, an import id is NOT stored in any
   * parser-maintained back-link set that gc/emit dereferences: gc and emit only
   * read `item.import` as an `Option`/bool and never call `imports.get(id)` on
   * a stored id (verified: no `imports.get(<id>)` call exists in walrus'
   * passes/emit). So a plain guarded delete is sufficient — there is no
   * back-link to clean. Id equality includes the arena_id, so this liveness
   * scan rejects BOTH already-deleted ids (`iter()` skips tombstoned entries)
   * AND handles that belong to a different module, surfacing a catchable JS
   * error instead of tripping walrus' `delete` assertion and aborting the
   * process across FFI.
   */
  delete(handle: WasmImport): void
  /**
   * Add an imported function under `moduleName`/`name`, returning a live handle
   * to the newly created (imported) function. The import record itself is
   * reachable via the returned handle's `import()`.
   *
   * `ty` is a CONSUME site for an arena id: walrus stores the raw `TypeId` and
   * resolves it to an index at emit via a panicking `get_type_index`; a
   * foreign-module or already-deleted type handle would abort the whole Node
   * process there. We reject such an id with a catchable error BEFORE touching
   * the arena, so a failed add never mutates the module. Same id-ref rule as
   * `tags.add` / the typed adds on `WasmExports`.
   */
  addFunction(moduleName: string, name: string, ty: WasmType): WasmFunction
  /**
   * Add an imported memory under `moduleName`/`name`, returning a live handle to
   * the newly created (imported) memory.
   *
   * `initial`/`maximum` are page counts (`bigint`, so 64-bit `memory64`
   * memories are representable losslessly); `maximum` is `null` for an
   * unbounded memory. `pageSizeLog2` is the custom-page-sizes proposal's log2
   * page size, or `null` for the default 64 KiB pages.
   *
   * MIRROR-WALRUS: the sizes are stored verbatim — no `initial <= maximum`
   * check (`WebAssembly.validate` is the user's tool). A negative or
   * out-of-`u64`-range size is still rejected (via `bigint_to_u64`), because
   * that is silent data corruption rather than a semantic-validity question.
   */
  addMemory(moduleName: string, name: string, shared: boolean, memory64: boolean, initial: bigint, maximum?: bigint | undefined | null, pageSizeLog2?: number | undefined | null): WasmMemory
  /**
   * Add an imported table under `moduleName`/`name`, returning a live handle to
   * the newly created (imported) table.
   *
   * `initial`/`maximum` are entry counts (`bigint`, so 64-bit `table64` tables
   * are representable losslessly); `maximum` is `null` for an unbounded table.
   * `elementType` must be a reference type (e.g. a `funcref`/`externref`
   * `{ type: 'Ref', ... }`); a non-reference type — or a concrete/indexed ref
   * type, which embeds a `TypeId` not yet threadable (deferred to the GC-types
   * task) — is rejected with a catchable error.
   *
   * Unlike `tables.addLocal`, a NON-NULLABLE element type is accepted: an
   * imported table carries no init segment (the host supplies the table), so a
   * non-nullable imported table is valid.
   *
   * MIRROR-WALRUS: the sizes are stored verbatim (no `initial <= maximum`
   * check); an out-of-`u64`-range size is still rejected (silent corruption).
   */
  addTable(moduleName: string, name: string, table64: boolean, initial: bigint, maximum: bigint | undefined | null, elementType: ValType): WasmTable
  /**
   * Add an imported global under `moduleName`/`name`, returning a live handle to
   * the newly created (imported) global.
   *
   * `ty` is the global's value type (e.g. `{ type: 'I32' }` or a `Ref`).
   * Fallible: a concrete/indexed ref type — which needs a type handle we do not
   * yet thread through — is rejected with a catchable error rather than
   * aborting. MIRROR-WALRUS otherwise.
   */
  addGlobal(moduleName: string, name: string, ty: ValType, mutable: boolean, shared: boolean): WasmGlobal
  /**
   * Add an imported tag under `moduleName`/`name`, returning a live handle to
   * the newly created (imported) tag. `ty` is the tag's (function) type
   * signature — for an exception tag its params are the exception's payload
   * value types.
   *
   * Same id-ref rule as [`WasmImports::add_function`]: `ty` must be a live type
   * in THIS module, or the stored `TypeId` would abort emit via a panicking
   * `get_type_index`. We reject a foreign/deleted type with a catchable error
   * BEFORE touching the arena.
   */
  addTag(moduleName: string, name: string, ty: WasmType): WasmTag
}

/**
 * A single local in a module, as a live handle: it holds the local's id plus a
 * strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmLocal {
  /**
   * This local's stable index — its identity for numeric lookup. Readable even
   * if the local is not (or no longer) in this module's arena (it never touches
   * the arena).
   */
  get index(): number
  /** This local's value type (read only — walrus exposes no setter). */
  get ty(): ValType
  /** This local's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this local's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
}

/**
 * The locals of a module. Each accessor materializes a fresh [`WasmLocal`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 *
 * NOTE: `ModuleLocals` is the MODULE-WIDE local arena — it holds every local
 * (and parameter) across all function bodies, not the locals of one function.
 * A local added here but never referenced by any function body is simply not
 * emitted (walrus drops unused locals), which is harmless.
 */
export declare class WasmLocals {
  /** The number of locals in the module (across all function bodies). */
  get length(): number
  /** Every local in the module, as live item handles. */
  items(): Array<WasmLocal>
  /** The local whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmLocal | null
  /**
   * Add a new local of the given value type, returning a live handle to it.
   *
   * `ty` is the local's value type (e.g. `{ type: 'I64' }` or a `Ref`).
   * Fallible: an unsupported `ty` — currently a concrete/indexed ref type,
   * which needs a type handle we do not yet thread through — is rejected with a
   * catchable error rather than aborting.
   *
   * The local is added to the module-wide arena; it only reaches the emitted
   * output if some function body references it. The returned handle holds its
   * own strong reference to the module (same as the accessor handles), so it
   * stays valid as long as it is held.
   */
  add(ty: ValType): WasmLocal
}

/**
 * The memories of a module. Each accessor materializes a fresh [`WasmMemory`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 */
export declare class WasmMemories {
  /** The number of memories in the module. */
  get length(): number
  /** Every memory in the module, as live item handles. */
  items(): Array<WasmMemory>
  /** The memory whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmMemory | null
  /**
   * Delete a memory from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted memory (walrus does not check).
   *
   * Same no-panic invariant as the item accessors: walrus'
   * `ModuleMemories::delete` asserts the id is live, and a panic across FFI
   * aborts the process. Id equality includes the arena_id, so this liveness
   * scan rejects BOTH already-deleted ids (`iter()` skips tombstoned entries)
   * AND handles that belong to a different module (arena_id mismatch),
   * surfacing a catchable JS error instead of aborting.
   */
  delete(memory: WasmMemory): void
  /**
   * Add a new locally defined memory, returning a live handle to it.
   *
   * `initial`/`maximum` are page counts (`bigint`, so 64-bit `memory64`
   * memories are representable losslessly); `maximum` is `null` for an
   * unbounded memory. `pageSizeLog2` is the custom-page-sizes proposal's log2
   * page size, or `null` for the default 64 KiB pages.
   *
   * The returned handle holds its own strong reference to the module (same as
   * the accessor handles), so it stays valid as long as it is held.
   */
  addLocal(shared: boolean, memory64: boolean, initial: bigint, maximum?: bigint | undefined | null, pageSizeLog2?: number | undefined | null): WasmMemory
}

/**
 * A single memory in a module, as a live handle: it holds the memory's id plus
 * a strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmMemory {
  /**
   * This memory's stable index — its identity for numeric lookup. Readable
   * even after the memory is deleted (it never touches the arena).
   */
  get index(): number
  /** This memory's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this memory's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /** Whether this memory is shared (a creation-time property, read only). */
  get shared(): boolean
  /** Whether this is a 64-bit memory (a creation-time property, read only). */
  get memory64(): boolean
  /** This memory's initial size, in wasm pages (`bigint`). */
  get initial(): bigint
  /** Set this memory's initial size, in wasm pages. */
  set initial(value: bigint)
  /**
   * This memory's optional maximum size, in wasm pages (`bigint`), or `null`
   * if unbounded.
   */
  get maximum(): bigint | null
  /** Set this memory's optional maximum size, in wasm pages. `null` clears it. */
  set maximum(value: bigint | undefined | null)
  /**
   * The log2 of this memory's custom page size (custom-page-sizes proposal),
   * or `null` for the default 64 KiB pages. Read only (creation-time).
   */
  get pageSizeLog2(): number | null
  /**
   * Whether this memory is imported. The import handle itself is exposed by a
   * later imports task; only the boolean is available now.
   */
  get isImported(): boolean
  /**
   * The import that brings this memory into the module, as a live
   * [`WasmImport`] handle, or `null` if this memory is locally defined.
   *
   * A method (not a getter) because it materializes a fresh wrapper on each
   * call. Wrapping the id is a pure cross-link (the reverse of
   * `WasmImport.memory()`); a later access on the returned handle self-guards
   * against the import having been deleted.
   */
  import(): WasmImport | null
}

export declare class WasmModule {
  /**
   * Construct a new module from the given path with the default
   * configuration.
   */
  static fromPath(path: string): WasmModule
  /** Construct a new module from the given path and configuration. */
  static fromFileWithConfig(path: string, config: ModuleConfig): WasmModule
  /**
   * Construct a new module from the in-memory wasm buffer with the default
   * configuration.
   */
  static fromBuffer(bytes: Uint8Array): WasmModule
  /** Construct a new module from the in-memory wasm buffer and configuration. */
  static fromBufferWithConfig(bytes: Uint8Array, config: ModuleConfig): WasmModule
  /** Emit this module into an in-memory wasm buffer. */
  emitWasm(demangle: boolean): Uint8Array
  /** Emit this module into a `.wasm` file at the given path. */
  emitWasmFile(path: string, demangle: boolean): void
  /** Write the GraphViz `.dot` representation of this module to the given path. */
  writeGraphvizDot(path: string): void
  /**
   * Run garbage collection passes over this module, removing items that are
   * not transitively referenced from any root (exports, the start function,
   * etc.).
   */
  gc(): void
  /** The name of this module, as stored in the wasm "name" custom section. */
  get name(): string | null
  /** Set the name of this module, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /**
   * This module's start function — run automatically at instantiation — as a
   * live [`WasmFunction`] handle, or `null` if the module has none.
   *
   * A pure id-wrap: `null` is returned only when no start is set, never as a
   * liveness check. If the stored start function was later deleted the returned
   * handle self-guards on its own accessors (and the module would abort at emit
   * — see `set_start`).
   */
  get start(): WasmFunction | null
  /**
   * Set (or clear, with `null`) this module's start function.
   *
   * Id-ref guarded: walrus stores the raw `FunctionId` and resolves it to an
   * index at emit via a panicking `get_function_index`, so a function handle
   * from a different module (or an already-deleted one) would abort the whole
   * Node process there. We reject such a handle with a catchable error BEFORE
   * storing it, leaving the current start unchanged. Passing `null` clears the
   * start unconditionally (always safe).
   */
  set start(start: WasmFunction | undefined | null)
  /**
   * This module's main memory — the first memory (wasm memory index 0) — as a
   * live [`WasmMemory`] handle, or `null` if the module has no memory.
   *
   * A documented convenience, NOT a walrus passthrough: walrus has no
   * `main_memory()` accessor, so "main memory" here means the conventional
   * first memory that single-memory modules use for all loads/stores.
   */
  get mainMemory(): WasmMemory | null
  /**
   * The `producers` custom section of this module, describing the tools that
   * produced it. Mutations through the returned object write back to this
   * module.
   */
  get producers(): WasmProducers
  /**
   * The custom sections of this module. Mutations through the returned object
   * write back to this module.
   */
  get customs(): WasmCustomSections
  /**
   * The globals of this module. Each handle materialized through the returned
   * object reads and writes back to this module.
   */
  get globals(): WasmGlobals
  /**
   * The memories of this module. Each handle materialized through the returned
   * object reads and writes back to this module.
   */
  get memories(): WasmMemories
  /**
   * The tables of this module. Each handle materialized through the returned
   * object reads and writes back to this module.
   */
  get tables(): WasmTables
  /**
   * The types of this module. Each handle materialized through the returned
   * object reads and writes back to this module.
   */
  get types(): WasmTypes
  /**
   * The functions of this module (imported and locally defined). Each handle
   * materialized through the returned object reads and writes back to this
   * module.
   */
  get functions(): WasmFunctions
  /**
   * The locals of this module (across all function bodies). Each handle
   * materialized through the returned object reads and writes back to this
   * module.
   */
  get locals(): WasmLocals
  /**
   * The data segments of this module. Each handle materialized through the
   * returned object reads and writes back to this module.
   */
  get data(): WasmDataSegments
  /**
   * The element segments of this module. Each handle materialized through the
   * returned object reads and writes back to this module.
   */
  get elements(): WasmElements
  /**
   * The tags (exception-handling tags) of this module. Each handle
   * materialized through the returned object reads and writes back to this
   * module.
   */
  get tags(): WasmTags
  /**
   * The imports of this module. Each handle materialized through the returned
   * object reads and writes back to this module.
   */
  get imports(): WasmImports
  /**
   * The exports of this module. Each handle materialized through the returned
   * object reads and writes back to this module.
   */
  get exports(): WasmExports
}

/**
 * The `producers` custom section of a module, exposing the tools that produced
 * it. Mutations write straight through to the owning [`WasmModule`].
 */
export declare class WasmProducers {
  /** Add (or update) a `language` entry in the producers section. */
  addLanguage(language: string, version: string): void
  /** Add (or update) a `processed-by` entry in the producers section. */
  addProcessedBy(tool: string, version: string): void
  /** Add (or update) an `sdk` entry in the producers section. */
  addSdk(sdk: string, version: string): void
  /** Remove every field from the producers section. */
  clear(): void
  /** List the fields currently present in the producers section. */
  fields(): Array<ProducerFieldInfo>
}

/**
 * A single table in a module, as a live handle: it holds the table's id plus a
 * strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmTable {
  /**
   * This table's stable index — its identity for numeric lookup. Readable even
   * after the table is deleted (it never touches the arena).
   */
  get index(): number
  /** This table's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this table's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /** Whether this is a 64-bit table (a creation-time property, read only). */
  get table64(): boolean
  /** This table's initial size, in entries (`bigint`). */
  get initial(): bigint
  /** Set this table's initial size, in entries. */
  set initial(value: bigint)
  /**
   * This table's optional maximum size, in entries (`bigint`), or `null` if
   * unbounded.
   */
  get maximum(): bigint | null
  /** Set this table's optional maximum size, in entries. `null` clears it. */
  set maximum(value: bigint | undefined | null)
  /**
   * This table's element type, always a reference type (read only).
   *
   * Represented as the `ValType::Ref` variant. Fallible: the ref's heap type
   * may embed a `#[non_exhaustive]` walrus heap variant a later 0.26.x adds;
   * that surfaces as a catchable JS error, never a process-aborting panic.
   */
  get elementTy(): ValType
  /**
   * This table's initializer expression, or `null` if it is null-initialized.
   *
   * A method (not a getter) because it materializes a fresh `ConstExpr`
   * wrapper on each call. Read only: building a table WITH an initializer is
   * deferred to a later task.
   */
  init(): ConstExpr | null
  /**
   * Whether this table is imported. The import handle itself is exposed by a
   * later imports task; only the boolean is available now.
   */
  get isImported(): boolean
  /**
   * The import that brings this table into the module, as a live [`WasmImport`]
   * handle, or `null` if this table is locally defined.
   *
   * A method (not a getter) because it materializes a fresh wrapper on each
   * call. Wrapping the id is a pure cross-link (the reverse of
   * `WasmImport.table()`); a later access on the returned handle self-guards
   * against the import having been deleted.
   */
  import(): WasmImport | null
}

/**
 * The tables of a module. Each accessor materializes a fresh [`WasmTable`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 */
export declare class WasmTables {
  /** The number of tables in the module. */
  get length(): number
  /** Every table in the module, as live item handles. */
  items(): Array<WasmTable>
  /** The table whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmTable | null
  /**
   * The module's single function (`funcref`) table, or `null` if it has none.
   *
   * Mirrors walrus' `main_function_table`: modules produced by compilers like
   * LLVM typically have exactly one function table for indirect calls. Rejects
   * with a catchable error if the module has more than one function table.
   */
  mainFunctionTable(): WasmTable | null
  /**
   * Delete a table from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted table (walrus does not check).
   *
   * Same no-panic invariant as the item accessors: walrus'
   * `ModuleTables::delete` asserts the id is live, and a panic across FFI
   * aborts the process. Id equality includes the arena_id, so this liveness
   * scan rejects BOTH already-deleted ids (`iter()` skips tombstoned entries)
   * AND handles that belong to a different module (arena_id mismatch),
   * surfacing a catchable JS error instead of aborting.
   */
  delete(table: WasmTable): void
  /**
   * Add a new locally defined table, returning a live handle to it.
   *
   * `initial`/`maximum` are entry counts (`bigint`, so 64-bit `table64` tables
   * are representable losslessly); `maximum` is `null` for an unbounded table.
   * `elementTy` must be a reference type (e.g. a `funcref`/`externref`
   * `{ type: 'Ref', ... }`); a non-reference type is rejected with a catchable
   * error.
   *
   * This builds a NULL-initialized table (no `init` expression), so
   * `elementTy` must be nullable — building a table with a non-nullable
   * element type needs an initializer, which is deferred to a later task.
   *
   * The returned handle holds its own strong reference to the module (same as
   * the accessor handles), so it stays valid as long as it is held.
   */
  addLocal(table64: boolean, initial: bigint, maximum: bigint | undefined | null, elementTy: ValType): WasmTable
}

/**
 * A single tag in a module, as a live handle: it holds the tag's id plus a
 * strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmTag {
  /**
   * This tag's stable index — its identity for numeric lookup. Readable even
   * after the tag is deleted (it never touches the arena).
   */
  get index(): number
  /** This tag's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this tag's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /** Whether this tag is imported or locally defined (read only). */
  get kind(): TagKindTag
  /**
   * This tag's type, as a live [`WasmType`] handle into the module's type
   * arena.
   *
   * A method (not a getter) because it materializes a fresh `WasmType` wrapper
   * on each call. For an exception tag this type's `params()` are the
   * exception's payload value types.
   */
  ty(): WasmType
  /**
   * The import that brings this tag into the module, as a live [`WasmImport`]
   * handle, or `null` if this tag is locally defined.
   *
   * A method (not a getter) because it materializes a fresh wrapper on each
   * call. Wrapping the id is a pure cross-link (the reverse of
   * `WasmImport.tag()`); a later access on the returned handle self-guards
   * against the import having been deleted.
   */
  import(): WasmImport | null
}

/**
 * The tags (exception-handling tags) of a module. Each accessor materializes a
 * fresh [`WasmTag`] handle that reads and writes straight through to the owning
 * [`WasmModule`]; the collection itself caches nothing.
 */
export declare class WasmTags {
  /** The number of tags in the module. */
  get length(): number
  /** Every tag in the module, as live item handles. */
  items(): Array<WasmTag>
  /** The tag whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmTag | null
  /**
   * Delete a tag from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted tag (walrus does not check; a dangling export or `throw`
   * instruction aborts at emit time). Unlike active data/element segments,
   * tags carry NO parser-maintained back-link set on any owner item (the only
   * `IdHashSet<Tag>` in walrus is the gc pass's own transient `Used` set, built
   * fresh from exports and `throw` sites each run), so a plain guarded delete
   * is sufficient — there is no back-link to clean.
   *
   * Same no-panic invariant as the item accessors: walrus' `ModuleTags::delete`
   * tombstones the arena entry and a later access asserts liveness, and a panic
   * across FFI aborts the process. Id equality includes the arena_id, so this
   * liveness scan rejects BOTH already-deleted ids (`iter()` skips tombstoned
   * entries) AND handles that belong to a different module (arena_id mismatch),
   * surfacing a catchable JS error instead of aborting.
   */
  delete(tag: WasmTag): void
  /**
   * Add a new locally defined tag with the given type, returning a live handle
   * to it. `ty` is the tag's (function) type signature — for an exception tag
   * its params are the exception's payload value types.
   *
   * Fallible: `ty` must be a live type in THIS module. walrus stores the raw
   * `TypeId` and resolves it to an index at emit time via a panicking
   * `get_type_index`; a foreign-module or already-deleted type handle would
   * abort the whole Node process there. We reject such an id with a catchable
   * error BEFORE touching the arena, so a failed add never mutates the module.
   * Same id-ref rule as `globals.addLocal` / `data.addActive`.
   *
   * The returned handle holds its own strong reference to the module (same as
   * the accessor handles), so it stays valid as long as it is held.
   */
  add(ty: WasmType): WasmTag
}

/**
 * A single type in a module, as a live handle: it holds the type's id plus a
 * strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmType {
  /**
   * This type's stable index — its identity for numeric lookup. Readable even
   * after the type is deleted (it never touches the arena).
   */
  get index(): number
  /**
   * This type's name, if any. walrus does not preserve type names through
   * parsing, so this is `null` for a freshly parsed type; it reflects a name
   * set in memory via the setter.
   */
  get name(): string | null
  /** Set this type's name. */
  set name(name: string | undefined | null)
  /**
   * This type's kind (`Function`, `Struct`, or `Array`). Only `Function`
   * types have `params()` / `results()`.
   */
  get kind(): TypeKind
  /**
   * This function type's parameter value types.
   *
   * A method (not a getter) because it can fail: it throws a catchable error
   * if this type is not a function type (a `Struct`/`Array` GC type). This is
   * deliberate — walrus' `Type::params` calls `unwrap_function()` and PANICS
   * on a non-function type, which would abort the process across FFI, so we
   * go through `as_function()` and surface an error instead.
   */
  params(): Array<ValType>
  /**
   * This function type's result value types.
   *
   * Same fallibility as [`WasmType::params`]: throws for a non-function type
   * rather than hitting walrus' `unwrap_function` panic.
   */
  results(): Array<ValType>
}

/**
 * The types of a module. Each accessor materializes a fresh [`WasmType`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 *
 * walrus keeps internal function-entry types in its type arena (one per local
 * function, used for multi-value block entries). walrus never assigns them an
 * emit index, so referencing one at emit aborts, and they are not
 * user-meaningful. This collection FILTERS them out of `length` / `items` /
 * `getByIndex` — identified via each local function's `MultiValue` entry-block
 * type — so it exposes only user-meaningful types and a user can never obtain a
 * handle to an entry type.
 */
export declare class WasmTypes {
  /** The number of types in the module. */
  get length(): number
  /** Every type in the module, as live item handles. */
  items(): Array<WasmType>
  /** The type whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmType | null
  /**
   * The first type with the given name, or `null` if none is named that.
   *
   * Note: walrus does not preserve type names through parsing, so this always
   * returns `null` for a freshly parsed module. It matches names set in
   * memory (via the `name` setter).
   */
  byName(name: string): WasmType | null
  /**
   * Delete a type from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted type (walrus does not check, and a dangling reference aborts at
   * emit time).
   *
   * Same no-panic invariant as the item accessors: walrus' `ModuleTypes::delete`
   * indexes the arena first, which panics on a deleted/foreign id, and a panic
   * across FFI aborts the process. Id equality includes the arena_id, so this
   * liveness scan rejects BOTH already-deleted ids (`iter()` skips tombstoned
   * entries) AND handles that belong to a different module (arena_id mismatch),
   * surfacing a catchable JS error instead of aborting.
   */
  delete(ty: WasmType): void
  /**
   * Add a new function type, returning a live handle to it.
   *
   * `params`/`results` are the function signature's value types. Fallible: an
   * unsupported value type — currently a concrete/indexed ref type, which
   * needs a type handle we do not yet thread through — is rejected with a
   * catchable error rather than aborting.
   *
   * walrus deduplicates structurally: adding a signature identical to an
   * existing type returns a handle to that existing type (the arena does not
   * grow). This mirrors walrus and is intended behavior.
   *
   * The returned handle holds its own strong reference to the module (same as
   * the accessor handles), so it stays valid as long as it is held.
   */
  add(params: Array<ValType>, results: Array<ValType>): WasmType
  /**
   * Find an existing function type with the given signature, or `null` if none
   * matches.
   *
   * Fallible only because an unsupported (concrete/indexed) ref type in the
   * query is rejected with a catchable error, same as `add`.
   */
  find(params: Array<ValType>, results: Array<ValType>): WasmType | null
}

/** An abstract heap type, mirroring `walrus::AbstractHeapType` 1:1. */
export declare const enum AbstractHeapType {
  /** The abstract `func` heap type (any function). */
  Func = 'Func',
  /** The abstract `extern` heap type (external/host references). */
  Extern = 'Extern',
  /** The abstract `any` heap type (any internal reference). */
  Any = 'Any',
  /** The abstract `none` heap type (bottom type for internal refs). */
  None = 'None',
  /** The abstract `noextern` heap type (bottom type for external refs). */
  NoExtern = 'NoExtern',
  /** The abstract `nofunc` heap type (bottom type for function refs). */
  NoFunc = 'NoFunc',
  /** The abstract `eq` heap type (comparable references: i31, struct, array). */
  Eq = 'Eq',
  /** The abstract `struct` heap type. */
  Struct = 'Struct',
  /** The abstract `array` heap type. */
  Array = 'Array',
  /** The abstract `i31` heap type (31-bit integers). */
  I31 = 'I31',
  /** The abstract `exn` heap type (exceptions). */
  Exn = 'Exn',
  /** The abstract `noexn` heap type (bottom type for exception refs). */
  NoExn = 'NoExn'
}

/**
 * The discriminant of a [`ConstExpr`], mirroring the five `walrus::ConstExpr`
 * variants 1:1.
 */
export declare const enum ConstExprKind {
  /** An immediate constant value (`i32`/`i64`/`f32`/`f64`/`v128`). */
  Value = 'Value',
  /** Reads another global's value (`global.get`). */
  Global = 'Global',
  /** A typed null reference (`ref.null`). */
  RefNull = 'RefNull',
  /** A function reference (`ref.func`). */
  RefFunc = 'RefFunc',
  /** An extended constant expression (a sequence of const operations). */
  Extended = 'Extended'
}

/**
 * Whether a data segment is active (auto-initialized into a memory at
 * instantiation) or passive (copied on demand via `memory.init`).
 *
 * Mirrors the discriminant of `walrus::DataKind` (`Active { memory, offset }` /
 * `Passive`). The active variant's memory and offset are read through the
 * [`WasmData::memory`] / [`WasmData::offset`] accessors, which return `null`
 * for a passive segment.
 */
export declare const enum DataKindTag {
  /** An active data segment (initialized into a memory at a fixed offset). */
  Active = 'Active',
  /** A passive data segment (copied on demand via `memory.init`). */
  Passive = 'Passive'
}

/**
 * Whether an element segment's items are a list of function references or a
 * list of constant expressions.
 *
 * Mirrors the discriminant of `walrus::ElementItems`
 * (`Functions(Vec<FunctionId>)` / `Expressions(RefType, Vec<ConstExpr>)`). The
 * two variants are read through the accessor methods
 * [`WasmElement::function_items`] (populated for `Functions`) and
 * [`WasmElement::expression_element_type`] / [`WasmElement::expression_items`]
 * (populated for `Expressions`), each of which returns `null` for the
 * non-matching variant. They are separate methods rather than one structured
 * object because the payloads are `#[napi]` class handles (`WasmFunction` /
 * `ConstExpr`), which napi cannot nest inside a `#[napi(object)]`.
 */
export declare const enum ElementItemsTag {
  /** The segment's items are function references (`Functions`). */
  Functions = 'Functions',
  /** The segment's items are constant expressions (`Expressions`). */
  Expressions = 'Expressions'
}

/**
 * Whether an element segment is passive, declared, or active.
 *
 * Mirrors the discriminant of `walrus::ElementKind` (`Passive` / `Declared` /
 * `Active { table, offset }`). The active variant's table and offset are read
 * through the [`WasmElement::table`] / [`WasmElement::offset`] accessors, which
 * return `null` for a passive or declared segment.
 */
export declare const enum ElementKindTag {
  /** A passive element segment (copied on demand via `table.init`). */
  Passive = 'Passive',
  /**
   * A declared element segment (referenced only by `ref.func`; not usable to
   * initialize a table).
   */
  Declared = 'Declared',
  /**
   * An active element segment (copied into a table at a fixed offset at
   * instantiation).
   */
  Active = 'Active'
}

/**
 * The kind of item an export exposes from a module.
 *
 * Mirrors the discriminant of `walrus::ExportItem`
 * (`Function`/`Table`/`Memory`/`Global`/`Tag`). The exported item itself is
 * read through the matching typed accessor on [`WasmExport`]
 * (`func`/`table`/`memory`/`global`/`tag`), each of which returns the handle
 * for its variant and `null` for the others.
 */
export declare const enum ExportItemTag {
  /** An exported function. */
  Function = 'Function',
  /** An exported table. */
  Table = 'Table',
  /** An exported memory. */
  Memory = 'Memory',
  /** An exported global. */
  Global = 'Global',
  /** An exported tag (exception handling). */
  Tag = 'Tag'
}

/**
 * Whether a function is imported, locally defined, or an uninitialized
 * placeholder.
 *
 * Mirrors the discriminant of `walrus::FunctionKind`
 * (`Import(ImportedFunction) | Local(LocalFunction) | Uninitialized(TypeId)`).
 * The companion accessors that expose the import handle or the function body
 * are deferred to later tasks; only the tag is exposed here.
 */
export declare const enum FunctionKindTag {
  /** An externally defined, imported function. */
  Import = 'Import',
  /** A locally defined function (has an in-module body). */
  Local = 'Local',
  /**
   * A locally defined function whose body has not been parsed yet. This is an
   * internal walrus transient (it should not appear on a fully parsed module),
   * exposed for completeness.
   */
  Uninitialized = 'Uninitialized'
}

/**
 * Whether a global is imported or locally defined.
 *
 * Mirrors the discriminant of `walrus::GlobalKind` (`Import(ImportId)` /
 * `Local(ConstExpr)`). The companion accessors that expose the import id or
 * the local initializer are deferred to a later task.
 */
export declare const enum GlobalKind {
  /** An imported global (its initializer lives in the host). */
  Import = 'Import',
  /** A locally defined global (has an in-module initializer). */
  Local = 'Local'
}

/**
 * A heap type for reference (`ValType::Ref`) values.
 *
 * The `Concrete` and `Exact` variants carry a `type_index` — the stable
 * `.index()` of the referenced type in the module's type arena. This is
 * display-only: an index alone cannot rebuild a walrus `TypeId`, so there is
 * no reverse conversion (read-only value layer).
 */
export type HeapType =
  | { type: 'Abstract', kind: AbstractHeapType }
  | { type: 'Concrete', typeIndex: number }
  | { type: 'Exact', typeIndex: number }

/**
 * The kind of item an import brings into a module.
 *
 * Mirrors the discriminant of `walrus::ImportKind`
 * (`Function`/`Table`/`Memory`/`Global`/`Tag`). The imported item itself is
 * read through the matching typed accessor on [`WasmImport`]
 * (`func`/`table`/`memory`/`global`/`tag`), each of which returns the handle
 * for its variant and `null` for the others.
 */
export declare const enum ImportKindTag {
  /** An imported function. */
  Function = 'Function',
  /** An imported table. */
  Table = 'Table',
  /** An imported memory. */
  Memory = 'Memory',
  /** An imported global. */
  Global = 'Global',
  /** An imported tag (exception handling). */
  Tag = 'Tag'
}

/**
 * A single field (e.g. `language`, `sdk`, `processed-by`) of the producers
 * section, along with its versioned values.
 */
export interface ProducerFieldInfo {
  name: string
  values: Array<ProducerValueInfo>
}

/** A single versioned value within a producers field. */
export interface ProducerValueInfo {
  name: string
  version: string
}

/** Information about a single custom section in the module. */
export interface RawSectionInfo {
  name: string
  data?: Uint8Array
}

/**
 * Whether a tag is imported or locally defined.
 *
 * Mirrors the discriminant of `walrus::TagKind` (`Import(ImportId)` /
 * `Local`). The companion accessor that exposes the import handle for an
 * imported tag is deferred to the imports task; only the tag is exposed here.
 */
export declare const enum TagKindTag {
  /** An imported tag (defined by the host). */
  Import = 'Import',
  /** A locally defined tag. */
  Local = 'Local'
}

/**
 * The kind of a wasm type: which composite-type shape it is.
 *
 * Mirrors the discriminant of `walrus::CompositeType`
 * (`Function | Struct | Array`). Only `Function` types have `params()` /
 * `results()`; the `Struct` / `Array` variants are the GC composite types and
 * their field types are not yet exposed (a later GC-types task).
 */
export declare const enum TypeKind {
  /** A function type: has parameter and result value types. */
  Function = 'Function',
  /** A GC struct type. */
  Struct = 'Struct',
  /** A GC array type. */
  Array = 'Array'
}

/**
 * A wasm value type.
 *
 * Generated as a TypeScript discriminated union keyed on `type`, e.g.
 * `{ type: 'I32' } | ... | { type: 'Ref'; nullable: boolean; heap: HeapType }`.
 *
 * `walrus::RefType { nullable, heap_type }` is inlined into the `Ref` variant;
 * there is no standalone `RefType` napi type.
 */
export type ValType =
  | { type: 'I32' }
  | { type: 'I64' }
  | { type: 'F32' }
  | { type: 'F64' }
  | { type: 'V128' }
  | { type: 'Ref', nullable: boolean, heap: HeapType }
