/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A wasm constant expression, used to initialize a global.
 *
 * Construct one with the factory statics ([`ConstExpr::i32`],
 * [`ConstExpr::ref_null`], ...) and pass it to `globals.addLocal`.
 */
export declare class ConstExpr {
  /** A constant `i32` value. */
  static i32(v: number): ConstExpr
  /**
   * A constant `i64` value.
   *
   * Takes a JS `bigint`. napi's `BigInt::get_i64` also reports whether the
   * value fit losslessly in an `i64`; we intentionally ignore that flag and
   * take the low 64 bits, mirroring wasm's wraparound `i64` semantics (an
   * out-of-range `bigint` is truncated, not rejected).
   */
  static i64(v: bigint): ConstExpr
  /**
   * A constant `f32` value.
   *
   * napi has no 32-bit float argument type, so this takes a JS `number`
   * (`f64`) and narrows it to `f32`.
   */
  static f32(v: number): ConstExpr
  /** A constant `f64` value. */
  static f64(v: number): ConstExpr
  /**
   * A constant `v128` value from exactly 16 little-endian bytes.
   *
   * Rejects any other length with a catchable error (never a process-aborting
   * panic). The byte order matches walrus' own `v128` decoding: byte 0 is the
   * least-significant.
   */
  static v128(bytes: Uint8Array): ConstExpr
  /**
   * A constant that reads the current value of another global
   * (`global.get $g`).
   */
  static globalGet(global: WasmGlobal): ConstExpr
  /**
   * A null reference of the given heap type (`ref.null`).
   *
   * `ref.null` is ALWAYS nullable — a non-nullable null is invalid wasm
   * (`WebAssembly.validate` rejects it), so this factory takes only the heap
   * type and always builds a nullable `RefType`.
   *
   * Fallible because the heap type conversion rejects concrete/indexed heap
   * types (they need a type handle, deferred to the GC-types task).
   */
  static refNull(heap: HeapType): ConstExpr
  /** Which kind of constant expression this is. */
  get kind(): ConstExprKind
}

export declare class ModuleConfig {
  constructor()
  /**
   * Sets a flag to whether DWARF debug sections are generated for this
   * module.
   *
   * By default this flag is `false`. Note that any emitted DWARF is
   * currently wildly incorrect and buggy, and is also larger than the wasm
   * itself!
   */
  generateDwarf(generateDwarf: boolean): this
  /**
   * Sets a flag to whether the custom "name" section is generated for this
   * module.
   *
   * The "name" section contains symbol names for the module, functions, and
   * locals. When enabled, stack traces will use these names, instead of
   * `wasm-function[123]`.
   *
   * By default this flag is `true`.
   */
  generateNameSection(generateNameSection: boolean): this
  /**
   * Sets a flag to whether synthetic debugging names are generated for
   * anonymous locals/functions/etc when parsing and running passes for this
   * module.
   *
   * By default this flag is `false`, and it will generate quite a few names
   * if enabled!
   */
  generateSyntheticNamesForAnonymousItems(generateSyntheticNamesForAnonymousItems: boolean): this
  /**
   * Indicates whether the module, after parsing, performs strict validation
   * of the wasm module to adhere with the current version of the wasm
   * specification.
   *
   * This can be expensive for some modules and strictly isn't required to
   * create a `Module` from a wasm file. This includes checks such as "atomic
   * instructions require a shared memory".
   *
   * By default this flag is `true`
   */
  strictValidate(strictValidate: boolean): this
  /**
   * Indicates whether the module will have the "producers" custom section
   * which preserves the original producers and also includes `walrus`.
   *
   * This is generally used for telemetry in browsers, but for otherwise tiny
   * wasm binaries can add some size to the binary.
   *
   * By default this flag is `true`
   */
  generateProducersSection(generateProducersSection: boolean): this
  /**
   * Indicates whether this module is allowed to use only stable WebAssembly
   * features or not.
   *
   * This is currently used to disable some validity checks required by the
   * WebAssembly specification. It's not religiously adhered to throughout
   * the codebase, even if set to `true` some unstable features may still be
   * allowed.
   *
   * By default this flag is `false`
   */
  onlyStableFeatures(onlyStableFeatures: boolean): this
  /**
   * Sets a flag to whether code transform is preverved during parsing.
   *
   * By default this flag is `false`.
   */
  preserveCodeTransform(preserve: boolean): this
  parse(binary: Uint8Array): WasmModule
}

/**
 * The custom sections of a module. Mutations write straight through to the
 * owning [`WasmModule`].
 */
export declare class WasmCustomSections {
  /**
   * Add a raw, unparsed custom section with the given name and data.
   *
   * Names starting with `.debug` are rejected: walrus manages DWARF debug
   * sections through its own parsed representation and silently drops any
   * `.debug*` custom section from `emitWasm` output, so adding one here would
   * be lost data. Add real debug info through the module's DWARF handling
   * instead.
   */
  addRaw(name: string, data: Uint8Array): void
  /**
   * Remove the first raw custom section with the given name, returning its
   * data if it was present.
   */
  removeRaw(name: string): Uint8Array | null
  /**
   * List the custom sections currently present in the module. `data` is the
   * raw bytes for unparsed (raw) sections, or `null` for sections that walrus
   * has parsed into a typed representation.
   */
  list(): Array<RawSectionInfo>
}

/**
 * A single global in a module, as a live handle: it holds the global's id plus
 * a strong reference to the owning [`WasmModule`], and every accessor reads or
 * writes through to that module.
 */
export declare class WasmGlobal {
  /**
   * This global's stable index — its identity for numeric lookup. Readable
   * even after the global is deleted (it never touches the arena).
   */
  get index(): number
  /** This global's name from the wasm "name" custom section, if any. */
  get name(): string | null
  /** Set this global's name, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /** Whether this global is mutable. */
  get mutable(): boolean
  /** Set whether this global is mutable. */
  set mutable(value: boolean)
  /** Whether this global is shared (a creation-time property, read only). */
  get shared(): boolean
  /** This global's value type (read only). */
  get ty(): ValType
  /** Whether this global is imported or locally defined (read only). */
  get kind(): GlobalKind
  /**
   * This global's constant initializer, or `null` if it is imported.
   *
   * A locally defined global carries a `ConstExpr` initializer; an imported
   * global's initial value lives in the host, so this returns `null` for it.
   * A method (not a getter) because it materializes a fresh `ConstExpr`
   * wrapper on each call.
   */
  init(): ConstExpr | null
}

/**
 * The globals of a module. Each accessor materializes a fresh [`WasmGlobal`]
 * handle that reads and writes straight through to the owning [`WasmModule`];
 * the collection itself caches nothing.
 */
export declare class WasmGlobals {
  /** The number of globals in the module. */
  get length(): number
  /** Every global in the module, as live item handles. */
  items(): Array<WasmGlobal>
  /** The global whose stable `.index` equals `index`, or `null` if none exists. */
  getByIndex(index: number): WasmGlobal | null
  /** The first global with the given name, or `null` if none is named that. */
  byName(name: string): WasmGlobal | null
  /**
   * Delete a global from the module. Takes the handle itself: a JS number can
   * never be turned back into a walrus id, so the wrapper is the only way to
   * name an item for removal.
   *
   * It is the caller's responsibility to ensure nothing still references the
   * deleted global (walrus does not check).
   *
   * Same no-panic invariant as the item accessors: walrus'
   * `ModuleGlobals::delete` asserts the id is live, and a panic across FFI
   * aborts the process. Id equality includes the arena_id, so this liveness
   * scan rejects BOTH already-deleted ids (`iter()` skips tombstoned entries)
   * AND handles that belong to a different module (arena_id mismatch),
   * surfacing a catchable JS error instead of aborting.
   */
  delete(global: WasmGlobal): void
  /**
   * Add a new locally defined global, returning a live handle to it.
   *
   * `ty` is the global's value type (e.g. `{ type: 'I32' }` or a `Ref`), and
   * `init` is its constant initializer (build one with the `ConstExpr`
   * factories). Fallible: an unsupported `ty` — currently a concrete/indexed
   * ref type, which needs a type handle we do not yet thread through — is
   * rejected with a catchable error rather than aborting.
   *
   * The returned handle holds its own strong reference to the module (same as
   * the accessor handles), so it stays valid as long as it is held.
   */
  addLocal(ty: ValType, mutable: boolean, shared: boolean, init: ConstExpr): WasmGlobal
}

export declare class WasmModule {
  /**
   * Construct a new module from the given path with the default
   * configuration.
   */
  static fromPath(path: string): WasmModule
  /** Construct a new module from the given path and configuration. */
  static fromFileWithConfig(path: string, config: ModuleConfig): WasmModule
  /**
   * Construct a new module from the in-memory wasm buffer with the default
   * configuration.
   */
  static fromBuffer(bytes: Uint8Array): WasmModule
  /** Construct a new module from the in-memory wasm buffer and configuration. */
  static fromBufferWithConfig(bytes: Uint8Array, config: ModuleConfig): WasmModule
  /** Emit this module into an in-memory wasm buffer. */
  emitWasm(demangle: boolean): Uint8Array
  /** Emit this module into a `.wasm` file at the given path. */
  emitWasmFile(path: string, demangle: boolean): void
  /** Write the GraphViz `.dot` representation of this module to the given path. */
  writeGraphvizDot(path: string): void
  /**
   * Run garbage collection passes over this module, removing items that are
   * not transitively referenced from any root (exports, the start function,
   * etc.).
   */
  gc(): void
  /** The name of this module, as stored in the wasm "name" custom section. */
  get name(): string | null
  /** Set the name of this module, stored in the wasm "name" custom section. */
  set name(name: string | undefined | null)
  /**
   * The `producers` custom section of this module, describing the tools that
   * produced it. Mutations through the returned object write back to this
   * module.
   */
  get producers(): WasmProducers
  /**
   * The custom sections of this module. Mutations through the returned object
   * write back to this module.
   */
  get customs(): WasmCustomSections
  /**
   * The globals of this module. Each handle materialized through the returned
   * object reads and writes back to this module.
   */
  get globals(): WasmGlobals
}

/**
 * The `producers` custom section of a module, exposing the tools that produced
 * it. Mutations write straight through to the owning [`WasmModule`].
 */
export declare class WasmProducers {
  /** Add (or update) a `language` entry in the producers section. */
  addLanguage(language: string, version: string): void
  /** Add (or update) a `processed-by` entry in the producers section. */
  addProcessedBy(tool: string, version: string): void
  /** Add (or update) an `sdk` entry in the producers section. */
  addSdk(sdk: string, version: string): void
  /** Remove every field from the producers section. */
  clear(): void
  /** List the fields currently present in the producers section. */
  fields(): Array<ProducerFieldInfo>
}

/** An abstract heap type, mirroring `walrus::AbstractHeapType` 1:1. */
export declare const enum AbstractHeapType {
  /** The abstract `func` heap type (any function). */
  Func = 'Func',
  /** The abstract `extern` heap type (external/host references). */
  Extern = 'Extern',
  /** The abstract `any` heap type (any internal reference). */
  Any = 'Any',
  /** The abstract `none` heap type (bottom type for internal refs). */
  None = 'None',
  /** The abstract `noextern` heap type (bottom type for external refs). */
  NoExtern = 'NoExtern',
  /** The abstract `nofunc` heap type (bottom type for function refs). */
  NoFunc = 'NoFunc',
  /** The abstract `eq` heap type (comparable references: i31, struct, array). */
  Eq = 'Eq',
  /** The abstract `struct` heap type. */
  Struct = 'Struct',
  /** The abstract `array` heap type. */
  Array = 'Array',
  /** The abstract `i31` heap type (31-bit integers). */
  I31 = 'I31',
  /** The abstract `exn` heap type (exceptions). */
  Exn = 'Exn',
  /** The abstract `noexn` heap type (bottom type for exception refs). */
  NoExn = 'NoExn'
}

/**
 * The discriminant of a [`ConstExpr`], mirroring the five `walrus::ConstExpr`
 * variants 1:1.
 */
export declare const enum ConstExprKind {
  /** An immediate constant value (`i32`/`i64`/`f32`/`f64`/`v128`). */
  Value = 'Value',
  /** Reads another global's value (`global.get`). */
  Global = 'Global',
  /** A typed null reference (`ref.null`). */
  RefNull = 'RefNull',
  /** A function reference (`ref.func`). */
  RefFunc = 'RefFunc',
  /** An extended constant expression (a sequence of const operations). */
  Extended = 'Extended'
}

/**
 * Whether a global is imported or locally defined.
 *
 * Mirrors the discriminant of `walrus::GlobalKind` (`Import(ImportId)` /
 * `Local(ConstExpr)`). The companion accessors that expose the import id or
 * the local initializer are deferred to a later task.
 */
export declare const enum GlobalKind {
  /** An imported global (its initializer lives in the host). */
  Import = 'Import',
  /** A locally defined global (has an in-module initializer). */
  Local = 'Local'
}

/**
 * A heap type for reference (`ValType::Ref`) values.
 *
 * The `Concrete` and `Exact` variants carry a `type_index` — the stable
 * `.index()` of the referenced type in the module's type arena. This is
 * display-only: an index alone cannot rebuild a walrus `TypeId`, so there is
 * no reverse conversion (read-only value layer).
 */
export type HeapType =
  | { type: 'Abstract', kind: AbstractHeapType }
  | { type: 'Concrete', typeIndex: number }
  | { type: 'Exact', typeIndex: number }

/**
 * A single field (e.g. `language`, `sdk`, `processed-by`) of the producers
 * section, along with its versioned values.
 */
export interface ProducerFieldInfo {
  name: string
  values: Array<ProducerValueInfo>
}

/** A single versioned value within a producers field. */
export interface ProducerValueInfo {
  name: string
  version: string
}

/** Information about a single custom section in the module. */
export interface RawSectionInfo {
  name: string
  data?: Uint8Array
}

/**
 * A wasm value type.
 *
 * Generated as a TypeScript discriminated union keyed on `type`, e.g.
 * `{ type: 'I32' } | ... | { type: 'Ref'; nullable: boolean; heap: HeapType }`.
 *
 * `walrus::RefType { nullable, heap_type }` is inlined into the `Ref` variant;
 * there is no standalone `RefType` napi type.
 */
export type ValType =
  | { type: 'I32' }
  | { type: 'I64' }
  | { type: 'F32' }
  | { type: 'F64' }
  | { type: 'V128' }
  | { type: 'Ref', nullable: boolean, heap: HeapType }
